spring:
  application:
    name: inconcert

  datasource:
    url: jdbc:mysql://localhost:3306/inconcert?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  # mail send (인증번호 전송)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail}
    password: ${googlePw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: INFO

jwt:
  secretKey: ${secretKey}
  refreshKey: ${refreshKey}
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000