spring:
  application:
    name: inconcert

  datasource:
    url: jdbc:mysql://localhost:3306/inconcert?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
